<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113102842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ged_id VARCHAR(255) NOT NULL, document_name VARCHAR(75) NOT NULL, responsable_name VARCHAR(50) NOT NULL, responsable_surname VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, subtype VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, last_update TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, origin VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document_third_party (document_id INT NOT NULL, third_party_id INT NOT NULL, PRIMARY KEY (document_id, third_party_id))');
        $this->addSql('CREATE INDEX IDX_B6C62948C33F7837 ON document_third_party (document_id)');
        $this->addSql('CREATE INDEX IDX_B6C6294854C4149C ON document_third_party (third_party_id)');
        $this->addSql('CREATE TABLE third_party (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) DEFAULT NULL, surname VARCHAR(50) DEFAULT NULL, phone VARCHAR(10) DEFAULT NULL, mail VARCHAR(50) DEFAULT NULL, ged_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE document_third_party ADD CONSTRAINT FK_B6C62948C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_third_party ADD CONSTRAINT FK_B6C6294854C4149C FOREIGN KEY (third_party_id) REFERENCES third_party (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_third_party DROP CONSTRAINT FK_B6C62948C33F7837');
        $this->addSql('ALTER TABLE document_third_party DROP CONSTRAINT FK_B6C6294854C4149C');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_third_party');
        $this->addSql('DROP TABLE third_party');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
